import Markdown from "markdown-to-jsx";

import createPageBase from "../components/PageLayout";

const exampleMarkdownContent = `
  # KIDATA markdown-to-jsx Demo

  <br>

  ## These elements were generated by markdown-to-jsx.

  markdown-to-jsx also supports HTML markup (though it is an inbuilt, so we may
  want to change the markdown processor)

  <br>
  <center>I can center this...</center>
  
  <center>
    Or add a video!
  
    <iframe 
      width="420"
      height="315"
      src="https://www.youtube.com/embed/xIKW3NKYBWw"
    />
  </center>

  <br>

  ### Header 3:

  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
  incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
  nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu 
  fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in 
  culpa qui officia deserunt mollit anim id est laborum.

  1. Here's
  2. a
  3. numbered
  4. list

  *and...*

  - Here's
  - a
  - bulleted
  - one
    - with
    - nested
      - bullets
  
  This page also expands with the size of its children, so this markdown file
  currently
`

function Home() {
  return createPageBase(
    <div className="page-card">
      <Markdown>{exampleMarkdownContent}</Markdown>
    </div>
  )
}

export default Home;